[
    {
        "name": "id",
        "dbType": "increments",
        "htmlType": "",
        "validations": "",
        "searchable": false,
        "fillable": false,
        "primary": true,
        "inForm": false,
        "inIndex": false,
        "inView": false
    },
    {
        "name": "vivape_id",
        "dbType": "string",
        "htmlType": "text",
        "validations": "nullable",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "email",
        "dbType": "string",
        "htmlType": "email",
        "validations": "nullable",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "phone",
        "dbType": "string",
        "htmlType": "text",
        "validations": "nullable",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "referring_code",
        "dbType": "string",
        "htmlType": "text",
        "validations": "nullable",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "referred_by_code",
        "dbType": "string",
        "htmlType": "text",
        "validations": "nullable",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "date_of_birth",
        "dbType": "date",
        "htmlType": "date",
        "validations": "nullable",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "date_of_joining",
        "dbType": "date",
        "htmlType": "date",
        "validations": "nullable",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "user_id",
        "dbType": "bigInteger:unsigned:foreign,users,id",
        "htmlType": "selectTable:users:name,id",
        "validations": "required",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "store_id",
        "dbType": "integer:unsigned:foreign,stores,id",
        "htmlType": "selectTable:stores:name,id",
        "validations": "required",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "country_id",
        "dbType": "integer:unsigned:foreign,countries,id",
        "htmlType": "selectTable:countries:name,id",
        "validations": "nullable",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "state_id",
        "dbType": "integer:unsigned:foreign,states,id",
        "htmlType": "selectTable:states:name,id",
        "validations": "nullable",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "city_id",
        "dbType": "integer:unsigned:foreign,cities,id",
        "htmlType": "selectTable:cities:name,id",
        "validations": "nullable",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "area_id",
        "dbType": "integer:unsigned:foreign,areas,id",
        "htmlType": "selectTable:areas:name,id",
        "validations": "nullable",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "address",
        "dbType": "text",
        "htmlType": "textarea",
        "validations": "nullable",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "identity",
        "dbType": "text",
        "htmlType": "textarea",
        "validations": "nullable",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "identity_type",
        "dbType": "string",
        "htmlType": "text",
        "validations": "nullable",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "identity_attachment",
        "dbType": "text",
        "htmlType": "file",
        "validations": "nullable",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "parent_type_id",
        "dbType": "integer:unsigned:foreign,parent_types,id",
        "htmlType": "selectTable:parent_types:name,id",
        "validations": "nullable",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "parent_category_id",
        "dbType": "integer:unsigned:foreign,parent_categories,id",
        "htmlType": "selectTable:parent_categories:name,id",
        "validations": "nullable",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "parent_status_id",
        "dbType": "integer:unsigned:foreign,parent_statuses,id",
        "htmlType": "selectTable:parent_statuses:name,id",
        "validations": "nullable",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "referance",
        "dbType": "string",
        "htmlType": "text",
        "validations": "nullable",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "code",
        "dbType": "string",
        "htmlType": "text",
        "validations": "nullable",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "title",
        "dbType": "string",
        "htmlType": "text",
        "validations": "nullable",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "name",
        "dbType": "string",
        "htmlType": "text",
        "validations": "nullable",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "level",
        "dbType": "string",
        "htmlType": "text",
        "validations": "nullable",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "index",
        "dbType": "string",
        "htmlType": "text",
        "validations": "nullable",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "index_min",
        "dbType": "string",
        "htmlType": "text",
        "validations": "nullable",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "index_max",
        "dbType": "string",
        "htmlType": "text",
        "validations": "nullable",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "status",
        "dbType": "string",
        "htmlType": "text",
        "validations": "nullable",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "type",
        "dbType": "string",
        "htmlType": "text",
        "validations": "nullable",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "category",
        "dbType": "string",
        "htmlType": "text",
        "validations": "nullable",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "ranking",
        "dbType": "string",
        "htmlType": "text",
        "validations": "nullable",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "priority",
        "dbType": "string",
        "htmlType": "text",
        "validations": "nullable",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "details",
        "dbType": "text",
        "htmlType": "textarea",
        "validations": "nullable",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "note",
        "dbType": "text",
        "htmlType": "textarea",
        "validations": "nullable",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "description",
        "dbType": "text",
        "htmlType": "textarea",
        "validations": "nullable",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "paremeters",
        "dbType": "text",
        "htmlType": "textarea",
        "validations": "nullable",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "attachment",
        "dbType": "text",
        "htmlType": "file",
        "validations": "nullable",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "created_by",
        "dbType": "bigInteger:unsigned:foreign,users,id",
        "htmlType": "selectTable:users:name,id",
        "validations": "nullable",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "updated_by",
        "dbType": "bigInteger:unsigned:foreign,users,id",
        "htmlType": "selectTable:users:name,id",
        "validations": "nullable",
        "searchable": true,
        "fillable": true,
        "primary": false,
        "inForm": true,
        "inIndex": true,
        "inView": true
    },
    {
        "name": "created_at",
        "dbType": "timestamp",
        "htmlType": "",
        "validations": "",
        "searchable": false,
        "fillable": false,
        "primary": false,
        "inForm": false,
        "inIndex": false,
        "inView": true
    },
    {
        "name": "updated_at",
        "dbType": "timestamp",
        "htmlType": "",
        "validations": "",
        "searchable": false,
        "fillable": false,
        "primary": false,
        "inForm": false,
        "inIndex": false,
        "inView": true
    },
    {
        "type": "relation",
        "relation": "mt1,Store,store_id,id"
    },
    {
        "type": "relation",
        "relation": "mt1,Country,country_id,id"
    },
    {
        "type": "relation",
        "relation": "mt1,State,state_id,id"
    },
    {
        "type": "relation",
        "relation": "mt1,City,city_id,id"
    },
    {
        "type": "relation",
        "relation": "mt1,Area,area_id,id"
    },
    {
        "type": "relation",
        "relation": "mt1,ParentType,parent_type_id,id"
    },
    {
        "type": "relation",
        "relation": "mt1,ParentCategory,parent_category_id,id"
    },
    {
        "type": "relation",
        "relation": "mt1,ParentStatus,parent_status_id,id"
    },
    {
        "type": "relation",
        "relation": "mt1,User,user_id,id"
    },
    {
        "type": "relation",
        "relation": "mt1,User,created_by,id"
    },
    {
        "type": "relation",
        "relation": "mt1,User,updated_by,id"
    }
]